services:
  alzaeshop-api:
    build:
      context: .
      dockerfile: AlzaEshop.API/Dockerfile
    container_name: alzaeshop-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - alzaeshop-network

networks:
  alzaeshop-network:
    driver: bridge