version: '3.8'

services:
  alzaeshop-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alzaeshop-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - alzaeshop-network

networks:
  alzaeshop-network:
    driver: bridge